### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by timsueberkrueb** [tim-sueberkrueb/ubuntu-hangups#12]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.6/lib/py/hangups/client.py", line 183, in _initialize_chat
    connector=self._connector
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.6/lib/py/hangups/http_utils.py", line 51, in fetch
    raise exceptions.NetworkError(error_msg)
hangups.exceptions.NetworkError: Request timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.6/backend/__init__.py", line 433, in run_asyncio_loop_in_thread
    loop.run_until_complete(client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.6/lib/py/hangups/client.py", line 109, in connect
    initial_data = yield from self._initialize_chat()
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.6/lib/py/hangups/client.py", line 189, in _initialize_chat
    .format(e))
hangups.exceptions.HangupsError: Failed to fetch PVT token: Request timed out
```

http://paste.ubuntu.com/12269747/
Reported by Carlos Raúl Laguna

**Comment by timsueberkrueb** [comment]
@tdryer Sorry for pinging you but I don't know how this should be handled.
What should the app do if the 'pvt' token couldn't get fetched? Why does this happen?
Thanks in advance :)

**Comment by tdryer** [comment]
This looks like a network issue (a request is timing out). hangups should already be retrying the request 3 times, so there isn't much else an application could do other than display an error.

**Comment by timsueberkrueb** [comment]
@tdryer okay, thanks for your answer.
