### ISSUE TITLE
Fails to show loaded conversations

### ISSUE THREAD

**Issue by cwayne18** [tim-sueberkrueb/ubuntu-hangups#2]
With the following traceback in the log:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(_self._args, *_self._kwargs)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/backend/__init__.py", line 433, in run_asyncio_loop_in_thread
    loop.run_until_complete(client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/lib/py/hangups/client.py", line 122, in connect
    yield from self._listen_future
  File "/usr/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/lib/py/hangups/channel.py", line 204, in listen
    yield from self._longpoll_request()
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/lib/py/hangups/channel.py", line 355, in _longpoll_request
    yield from self._on_push_data(chunk)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/lib/py/hangups/channel.py", line 382, in _on_push_data
    yield from self.on_connect.fire()
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/lib/py/hangups/event.py", line 50, in fire
    yield from gen
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/lib/py/hangups/client.py", line 114, in _on_connect
    yield from self.on_connect.fire(initial_data)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/lib/py/hangups/event.py", line 50, in fire
    yield from gen
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/backend/__init__.py", line 300, in on_connect
    ctrl = ConversationController(conv)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/backend/**init**.py", line 61, in **init**
    self.on_event(event)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/backend/**init**.py", line 89, in on_event
    self.handle_message(conv_event, user, set_unread=set_unread)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/backend/**init**.py", line 70, in handle_message
    for a in conv_event.attachments],
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/backend/**init**.py", line 70, in <listcomp>
    for a in conv_event.attachments],
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/backend/cache.py", line 52, in get_image_cached
    cache_image(url)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.1.4/backend/cache.py", line 47, in cache_image
    urllib.request.urlretrieve (url, images_path + get_image_cache_name(url))
  File "/usr/lib/python3.4/urllib/request.py", line 196, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/phablet/.local/share/ubuntu-hangups.timsueberkrueb/cache/images/img2616062347.com/-7exm4gju4wg/u3px6yetcwi/aaaaaaaab4i/0efxiw6c7fo/s0/2014-05-14'

Note: if i touch that file and restart, it seems to work..

**Comment by timsueberkrueb** [comment]
@cwayne18 An update with the fix is published. Can you tell me whether it works for you now?

**Comment by cwayne18** [comment]
@tim-sueberkrueb works like a charm, thanks!
