### ISSUE TITLE
Image sending doesn't work since v0.2.2

### ISSUE THREAD

**Issue by timsueberkrueb** [tim-sueberkrueb/ubuntu-hangups#21]
```
Exception in callback ConversationController.on_message_sent(<Task finishe...ge object.',)>)
handle: <Handle ConversationController.on_message_sent(<Task finishe...ge object.',)>)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.2.2/backend/__init__.py", line 193, in on_message_sent
    future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.2.2/lib/py/hangups/conversation.py", line 225, in send_message
    delivery_medium=self._get_default_delivery_medium()
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.2.2/lib/py/hangups/client.py", line 388, in sendchatmessage
    photo=hangouts_pb2.Photo(photo_id=image_id)
  File "/opt/click.ubuntu.com/ubuntu-hangups.timsueberkrueb/0.2.2/lib/py/google/protobuf/internal/python_message.py", line 668, in setter
    '"%s" in protocol message object.' % proto_field_name)
AttributeError: Assignment not allowed to composite field "existing_media" in protocol message object.
```

**Comment by tdryer** [comment]
Fixed in hangups here: https://github.com/tdryer/hangups/commit/3c9e449a22d4dbd920eaaa092e7926e867029e21

**Comment by timsueberkrueb** [comment]
@tdryer wow, thank you so much!!!
